#!/usr/bin/env python3
"""Generate the document-level train/validation/test split, once.

    python scripts/make_splits.py

Writes data/splits/{train,validation,test}.txt — plain lists of doc_ids that
are committed to the repository and read by every downstream script.

Splitting is by document: every sentence of a post lands in the same split, so
no post leaks across the boundary.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from turengmix.data import DEFAULT_BENCHMARK, DEFAULT_SPLIT_DIR, load_benchmark  # noqa: E402

HEADER = (
    "# TurEngMix document-level split — {name}\n"
    "# {n} documents, {t} tokens. Generated by scripts/make_splits.py "
    "(seed={seed}, ratios={ratios}).\n"
    "# Committed deliberately: regenerating is not stable across Python "
    "versions. Do not edit by hand.\n"
)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--benchmark", type=Path, default=DEFAULT_BENCHMARK)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_SPLIT_DIR)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--train", type=float, default=0.80)
    ap.add_argument("--validation", type=float, default=0.10)
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing split (this changes reported numbers)")
    args = ap.parse_args()

    existing = [args.out_dir / f"{n}.txt" for n in ("train", "validation", "test")]
    if any(p.exists() for p in existing) and not args.force:
        print("A split already exists in", args.out_dir)
        print("Every number in the paper is tied to it. Pass --force only if you "
              "intend to invalidate previously computed results.")
        return 1

    df = load_benchmark(args.benchmark)
    tokens_per_doc = df.groupby("doc_id").size().to_dict()

    # Ordered by the unique trailing document number, which is also the order
    # the documents appear in the raw export, then shuffled with seed 42. This
    # reproduces Table 7 of the paper exactly: 200/25/25 posts, 254/26/41
    # sentences, 12,466/1,173/1,373 tokens. Do not change the ordering or the
    # seed without regenerating every reported result.
    doc_ids = sorted(tokens_per_doc, key=lambda d: int(d.rsplit("_", 1)[-1]))
    random.Random(args.seed).shuffle(doc_ids)

    n = len(doc_ids)
    n_train = int(args.train * n)
    n_val = int(args.validation * n)
    parts = {
        "train": doc_ids[:n_train],
        "validation": doc_ids[n_train:n_train + n_val],
        "test": doc_ids[n_train + n_val:],
    }

    args.out_dir.mkdir(parents=True, exist_ok=True)
    ratios = f"{args.train}/{args.validation}/{round(1 - args.train - args.validation, 4)}"
    for name, docs in parts.items():
        docs = sorted(docs)
        tokens = sum(tokens_per_doc[d] for d in docs)
        path = args.out_dir / f"{name}.txt"
        with open(path, "w", encoding="utf-8") as f:
            f.write(HEADER.format(name=name, n=len(docs), t=tokens,
                                  seed=args.seed, ratios=ratios))
            f.write("\n".join(docs) + "\n")
        print(f"{name:<11} {len(docs):>4} documents  {tokens:>7,} tokens  -> {path}")

    paper = {"train": (200, 12466), "validation": (25, 1173), "test": (25, 1373)}
    match = all((len(parts[n]), sum(tokens_per_doc[d] for d in parts[n])) == p
                for n, p in paper.items())
    print()
    print("reproduces Table 7 of the paper: " + ("yes" if match else "NO — check --seed"))
    if not match:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
